export const INCREASE = "INCREASE";
export const DECREASE = "DECREASE";
export const DISPATCH_ARTISTS = "DISPATCH_ARTISTS";
export const DISPATCH_ARTIST_DATE = "DISPATCH_ARTIST_DATE";
export const DISPATCH_ARTIST_HOUR = "DISPATCH_ARTIST_HOUR";
export const SELECTED_SERVICE = "SELECT_SERVICE";
export const SELECTED_ARTIST = "SELECTED_ARTIST";
export const SELECTED_DATE = "SELECTED_DATE";
export const SELECTED_HOUR = "SELECTED_HOUR";

export const RESET = "RESET";
export const RESET_SERVICES = "RESET_SERVICES";
export const RESET_ARTISTS = "RESET_ARTISTS";
export const RESET_DATES = "RESET_DATES";
export const RESET_HOURS = "RESET_HOURS";
export const RESET_RESERVE_INFO = "RESET_RESERVE_INFO";
export const RESERVATION_COMPLETED ="RESERVATION_COMPLETED"; 
export const RESERVATION_CANCELLD = "RESERVATION_CANCELLD";

export const SHOW_lOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";